name: Laravel Tests

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: solid_app
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      mailpit:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Update the PHP version to 8.2
          extensions: "mbstring, zip, exif, pcntl, pdo, mysql, tokenizer, bcmath, gd, xml, curl"
          coverage: "none"

      - name: Copy .env file
        run: cp .env.example .env

      - name: Install Dependencies
        run: |
          composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

      - name: Generate Laravel key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test
