name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: default
          MYSQL_DATABASE: solid_app
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.3"
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          registry-url: https://registry.npmjs.org/

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Update composer dependencies
        run: composer update

      - name: Install PHPUnit
        run: |
          composer require --dev phpunit/phpunit:^10.5
          composer install

      - name: Dump autoload
        run: composer dump-autoload --optimize --no-interaction

      - name: Compile frontend assets
        run: |
          npm install
          npm run build

      - name: Generate key
        run: php artisan key:generate

      - name: Clear Config
        run: php artisan config:clear

      - name: Clear Optimize
        run: php artisan optimize:clear

      - name: Cache Config
        run: php artisan config:cache

      - name: Run Migration
        run: php artisan migrate -v

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test
