name: PHP Code styling with Pint
on:
  workflow_dispatch:
  push:
jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@0.1.0
        with:
          preset: laravel

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.PINT_TOKEN }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
